config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
  	resources :sections, only: [:update] do 
  		resources :lessons, only: [:create]
  	end
  	resources :courses, only: [:new, :create, :show] do
  		resources :sections, only: [:create]
		end  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :user
	has_many :sections
	has_many :enrollments

	validates :title, presence: true
	validates :description, presence: true
	validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

	def free?
		cost.zero?
	end

	def premium?
		! free?
	end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	belongs_to :section
	mount_uploader :video, VideoUploader

	include RankedModel
	ranks :row_order, with_same: :section_id

	def next_lesson
		lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
		if lesson.blank? && section.next_section
			return section.next_section.lessons.rank(:row_order).first
		end
		return lesson
	end
end

app/models/section.rb
class Section < ApplicationRecord
	belongs_to :course
	has_many :lessons

	include RankedModel
	ranks :row_order, with_same: :course_id

	def next_section
		section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
		return section
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :courses
	has_many :enrollments
	has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def enrolled_in?(course)
  	return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :authenticate_user!
	
	def show
	end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	before_action :authenticate_user!

	def create
		if current_course.premium?
			# Amount in cents
	    @amount = (current_course.cost * 100).to_i

	    customer = Stripe::Customer.create(
	      email: params[:stripeEmail],
	      source: params[:stripeToken]
	    )

	    charge = Stripe::Charge.create(
	      customer: customer.id,
	      amount: @amount,
	      description: 'Level Up Course Enrollment',
	      currency: 'usd'
	    )
	  end

    current_user.enrollments.create(course: current_course)
	  redirect_to course_path(current_course)
	  rescue Stripe::CardError => e
	    flash[:error] = e.message
	    redirect_to root_path
	end

	private

	def current_course
		@current_course ||= Course.find(params[:course_id])
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_enrollment_for_current_lesson, only: [:show]

	def show
		@lesson = current_lesson
	end

	private

	def require_enrollment_for_current_lesson
	 	unless current_user.enrolled_in?(current_lesson.section.course)
	  	redirect_to courses_path, alert: 'Must be enrolled to access'
	  end
	end

	helper_method :current_lesson
	def current_lesson
		@current_lesson ||= Lesson.find(params[:id])
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

	def privacy
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://vjs.zencdn.net/7.6.0/video-js.css" rel="stylesheet">
    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  </head>

  <body>
    <!-- Flex Box Element -->
    <div id="flex-content-container">
      <!-- Navigation Bar -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Level up', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to 'See All Courses', courses_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'My Dashboard', dashboard_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up!', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <!-- Alerts for Devise -->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <!-- Render View -->
    <%= yield %>

    <!-- Flexbox Footer-->
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-3 text-center">
            <b>Teachers</b>
            <br>
            <%= link_to 'My Dashboard', dashboard_path %>
            <br>
            <%= link_to 'Create Course', new_instructor_course_path %>
            <br>
            <%= link_to 'Privacy Policy', privacy_path %>
          </div>
          <div class="col-12 col-sm-3 text-center">
            <b>Students</b>
            <br>
            <%= link_to 'My Courses', dashboard_path %>
            <br>
            <%= link_to 'Last Lesson', '#' %>
            <br>
            <%= link_to 'Privacy Policy', privacy_path %>
          </div>
          <div class="col-12 col-sm-3 text-center">
            <b>Resources</b>
            <br>
            <a href="https://google.com">Google</a>
            <br>
            <a href="https://codeschool.com">Code School</a>
            <br>
            <a href="https://khanacademy.com">Khan Academy</a>
          </div>
          <div class="col-12 col-sm-3 text-center social">
            <b>Contact</b>
            <br>
            <b>Developer</b>
            <br>
            <%= link_to 'http://github.com/Thirdeyeclimber', target: :_blank do %>
              <span class="fa fa-github-square fa-2x social-button"></span>
            <% end %>
            <%= link_to 'https://www.linkedin.com/in/webdev10100/', target: :_blank do %>
              <span class="fa fa-linkedin-square fa-2x"></span>
            <% end %>
            <%= link_to 'https://twitter.com/Thirdeyeclimber', target: :_blank do %>
              <span class="fa fa-twitter-square fa-2x"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <script src='https://vjs.zencdn.net/7.6.0/video.js'></script>
  </body>
</html>